# -*- mode: ruby -*-
# vi: set ft=ruby :
require_relative 'provisioning/vbox.rb'
VBoxUtils.check_version('7.2.4')
Vagrant.require_version ">= 2.4.9"

STUDEN_PREFIX = "srg2526"
BOX_NAME = "srg2526/debian-13"

Vagrant.configure("2") do |config|
  config.vm.box = BOX_NAME
  config.vm.hostname = "#{STUDEN_PREFIX}-ansible"
  config.vm.network "forwarded_port", guest: 80, host: 8080

  # Configure hostmanager plugin
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true

  config.vm.provider "virtualbox" do |vb|
	  vb.name = "AISI-P3-EJ2-#{config.vm.hostname}"
	  vb.cpus = 1
	  vb.memory = 1024
	  vb.gui = false
	  vb.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
  end

  config.vm.provision "ansible", run: "once", type: "ansible_local" do |ansible|
	  ansible.install = "true"
	  ansible.install_mode = "pip3"
	  ansible.playbook = "provisioning/playbook.yml"
  end
end
